baseURL = "http://guumaster.github.io/"
languageCode = "en-us"
title = "Guumaster"
theme = "minimal"

[params]
    author = "Guumaster"
    description = "Another blog to remember things I did"
    githubUsername = "guumaster"
    accent = "#3252af"
    showBorder = true
    backgroundColor = "#e6e6e6"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "javascript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:guuweb@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/guumaster/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/guumaster/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/gustavoandresmarin/"
    name = "linkedin"
    weight = 4

